name: Atom Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ok-nick/setup-aftman@v0.4.2
        with:
          version: v0.3.0
          path: "."
          cache: false
          token: ${{ github.token }}
              
      - name: "aftman install"
        run: aftman install

      - uses: NTBBloodbath/selene-action@v0.3.2
        with:
          token: ${{ github.token }}