name: Atom Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "install aftman"
        run: ./aftman self-install

      - name: "aftman install"
        run: ./aftman install

      - name: "lint"
        run: selene src