name: Atom Pipeline

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout    
        uses: actions/checkout@v4.2.2

      - uses: ok-nick/setup-aftman@v0.4.2
        with:
          version: v0.3.0
          path: "."
          cache: false
          token: ${{ github.token }}
              
      - name: "aftman install"
        run: aftman install
  
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout    
        uses: actions/checkout@v4.2.2

      - uses: NTBBloodbath/selene-action@v1.0.0
        with:
          token: ${{ github.token }}
          args: src