name: Atom Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "aftman install"
        run: aftman install

      - name: "lint"
        run: selene src